# I an really pissed that pnp is not working for me.
# anyway this is a lifesaver setting for yarn. to use node modules in their classic old way.
nodeLinker: node-modules
# I think this suggests the path of yarn version and stuff
yarnPath: .yarn/releases/yarn-berry.cjs
